spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/school?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=TRUE&serverTimezone=UTC
    username: root
    password: 145132
mybatis:

  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
